//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReqTrackit.website.Models.ReqTrackModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class nuget_request_tracker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nuget_request_tracker()
        {
            this.request_tracker = new HashSet<request_tracker>();
        }
    
        public string Id { get; set; }
        public int PackageID { get; set; }
        public string TFS_BranchName { get; set; }
        public string TFS_changeset { get; set; }
        public string Version_requested { get; set; }
        public string Description { get; set; }
    
        public virtual package_details package_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<request_tracker> request_tracker { get; set; }
    }
}
