//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReqTrackit.website.Models.ReqTrackModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReqTrackEnities : DbContext
    {
        public ReqTrackEnities()
            : base("name=ReqTrackEnities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<nuget_request_tracker> nuget_request_tracker { get; set; }
        public virtual DbSet<package_details> package_details { get; set; }
        public virtual DbSet<request_status> request_status { get; set; }
        public virtual DbSet<request_tracker> request_tracker { get; set; }
        public virtual DbSet<request_type> request_type { get; set; }
    }
}
