//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReqTrackit.website.Models.ReqTrackModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class request_tracker
    {
        public int Id { get; set; }
        public int TypeID { get; set; }
        public int StatusID { get; set; }
        public string DetailsID { get; set; }
        public string UserID { get; set; }
        public System.DateTime Date_requested { get; set; }
        public Nullable<System.DateTime> Date_completed { get; set; }
    
        public virtual nuget_request_tracker nuget_request_tracker { get; set; }
        public virtual request_status request_status { get; set; }
        public virtual request_type request_type { get; set; }
    }
}
